#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo "Starting policy enforcement hardening environment..."

# Backend service
if [ -f "src/main.py" ]; then
    echo "Starting backend service..."
    python src/main.py &
    BACKEND_PID=$!
    echo "Backend started with PID: $BACKEND_PID"
else
    echo "Warning: src/main.py not found"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
if [ -f "src/main.py" ]; then
    echo "  Backend: Running (PID: $BACKEND_PID)"
fi
echo ""
echo "To run tests:"
echo "  pytest tests/"
echo ""
echo "To test the policy engine:"
echo "  python -c \"from src.core.policy import PolicyEngine; p = PolicyEngine(); print(p.check_permission('app.open', {}))\""
echo ""